language: php

php:
  - 7.1
  - 7.2
  - 7.3

branches:
  only:
  - master

before_script:
  - composer install

script:
  - vendor/phpunit/phpunit/phpunit --configuration phpunit.xml.dist --coverage-text
